version: "3.9"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80-83:80"
    deploy:
      replicas: 2
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
